export default [
    'Work Sans, sans-serif',
    'Playfair Display, serif',
    'Libre Franklin, sans-serif',
    'Space Mono, monospace',
    'Rubik, sans-serif',
    'Cormorant, serif',
    'Fira Sans, sans-serif',
    'Eczar, serif',
    'Alegreya Sans, sans-serif',
    'Alegreya, serif',
    'Chivo, sans-serif',
    'Lora, serif',
    'Source Sans Pro, sans-serif',
    'Source Serif Pro, serif',
    'Roboto, sans-serif',
    'Roboto Slab, serif',
    'Poppins, sans-serif',
    'BioRhyme, serif',
    'Archivo Narrow, sans-serif',
    'Libre Baskerville, serif',
    'Crimson Text, serif',
    'Karla, sans-serif',
    'Montserrat, sans-serif',
    'Proza Libre, sans-serif',
    'Spectral, serif',
    'Domine, serif',
    'Bitter, serif',
    'Inknut Antiqua, serif',
    'PT Sans, sans-serif',
    'PT Serif, serif',
    'Lato, sans-serif',
    'Cardo, serif',
    'Neuton, serif',
    'Open Sans, sans-serif',
    'Inconsolata, monospace',
    'Cabin, sans-serif',
    'Raleway, sans-serif',
    'Anonymous Pro, monospace',
    'Arvo, serif',
    'Merriweather, serif',
];